{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# DeBERTaV3 - Task B"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Instructions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "tags": [
     "parameters"
    ]
   },
   "source": [
    "The function of this notebook is to act like a frontend to the code for model testing.\n",
    "In practice, this means each new code cell is meant to represent one test, where the parameters of the model are used, and the output of the test can be stored.\n",
    "\n",
    "Example:\n",
    "```\n",
    "!python program_name.py \\\n",
    "--learning_rate \\\n",
    "--batch_size \\\n",
    "etc.\n",
    "```\n",
    "\n",
    "After the tests you want to run are finished, the notebook can be pushed to the repository for storage of the parameters and full output.\n",
    "\n",
    "**Important:**\n",
    "- If major changes have been made to the code before new tests, add this into a markdown cell before any new tests.\n",
    "- Always make sure to pull the latest changes before running new tests."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Testing"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**model** [*microsoft/deberta-v3-base*](https://huggingface.co/microsoft/deberta-v3-base)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def tester(script_name, task, test_num, model_name, epochs, learning_rate, batch_size, sequence_length, task_b_mode):\n",
    "    if task == 'a':\n",
    "        print(f'\\n\\n{model_name}\\n\\nTest: {test_num}\\n\\nRunning task {task.upper()} through {script_name}')\n",
    "        print(f'The following settings are used:\\n - epochs: {epochs}\\n - learning rate: {learning_rate}\\n - batch size: {batch_size}\\n - sequence length: {sequence_length}\\n\\n')\n",
    "        !python '{script_name}' --transformer {model_name} --save_model {model_name.split('/')[-1]}_task_{task}_test{test_num} --epochs {epochs} --learn_rate {learning_rate} --batch_size {batch_size} --sequence_length {sequence_length}\n",
    "\n",
    "    elif task == 'b':\n",
    "        for mode in task_b_mode:\n",
    "            print(f'\\n\\n{model_name}\\n\\nTest: {test_num}\\n\\nRunning task {task.upper()} through {script_name}')\n",
    "            print(f'The following settings are used:\\n - mode: {mode}\\n - epochs: {epochs}\\n - learning rate: {learning_rate}\\n - batch size: {batch_size}\\n - sequence length: {sequence_length}\\n\\n')\n",
    "            !python '{script_name}' --transformer {model_name} --save_model {model_name.split('/')[-1]}_task_{task}_test{test_num}_{mode} --epochs {epochs} --learn_rate {learning_rate} --batch_size {batch_size} --sequence_length {sequence_length} --task_b --mode {mode}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "microsoft/deberta-v3-base\n",
      "\n",
      "Test: 3\n",
      "\n",
      "Running task B through models both.py\n",
      "The following settings are used:\n",
      " - mode: concat\n",
      " - epochs: 10\n",
      " - learning rate: 5e-05\n",
      " - batch size: 8\n",
      " - sequence length: 100\n",
      "\n",
      "\n",
      "2022-12-19 20:31:57.791486: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 20:31:57.894249: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2022-12-19 20:31:58.284268: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 20:31:58.284310: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 20:31:58.284317: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "Running deberta-v3-base for task B\n",
      "Training model: microsoft/deberta-v3-base\n",
      "With parameters:\n",
      "Learn rate: 5e-05, Batch size: 8\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "2022-12-19 20:32:01.887957: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:32:01.893750: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:32:01.898024: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:32:01.899796: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 20:32:01.901227: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:32:01.903130: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:32:01.905018: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:32:02.281261: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:32:02.282060: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:32:02.282678: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:32:02.283274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5582 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:0b:00.0, compute capability: 8.6\n",
      "2022-12-19 20:32:02.956279: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "All model checkpoint layers were used when initializing TFDebertaV2ForSequenceClassification.\n",
      "\n",
      "Some layers of TFDebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['pooler', 'cls_dropout', 'classifier']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_tf_deberta_v2.py:125: Bernoulli.__init__ (from tensorflow.python.ops.distributions.bernoulli) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/distributions/bernoulli.py:86: Distribution.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "1400/1400 [==============================] - 229s 153ms/step - loss: 0.8468 - accuracy: 0.7579 - val_loss: 0.8438 - val_accuracy: 0.7543\n",
      "Epoch 2/10\n",
      "1400/1400 [==============================] - 211s 151ms/step - loss: 0.8403 - accuracy: 0.7580 - val_loss: 0.8460 - val_accuracy: 0.7543\n",
      "Epoch 3/10\n",
      " 918/1400 [==================>...........] - ETA: 1:09 - loss: 0.8480 - accuracy: 0.7538^C\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 393, in <module>\n",
      "    main()\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 378, in main\n",
      "    model = train_transformer(args.transformer, ep, bs, lr, sl, X_train, Y_train, X_dev, Y_dev, args.task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 178, in train_transformer\n",
      "    model.fit(tokens_train, Y_train_bin, verbose=1, epochs=epoch,\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/training.py\", line 1564, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py\", line 915, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py\", line 947, in _call\n",
      "    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/function.py\", line 2496, in __call__\n",
      "    return graph_function._call_flat(\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/function.py\", line 1862, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function.call(\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/function.py\", line 499, in call\n",
      "    outputs = execute.execute(\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 54, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "KeyboardInterrupt\n",
      "\n",
      "\n",
      "microsoft/deberta-v3-base\n",
      "\n",
      "Test: 3\n",
      "\n",
      "Running task B through models both.py\n",
      "The following settings are used:\n",
      " - mode: shuffle\n",
      " - epochs: 10\n",
      " - learning rate: 5e-05\n",
      " - batch size: 8\n",
      " - sequence length: 100\n",
      "\n",
      "\n",
      "2022-12-19 20:41:37.639987: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 20:41:37.738494: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2022-12-19 20:41:38.128120: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 20:41:38.128161: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 20:41:38.128169: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "Running deberta-v3-base for task B\n",
      "Training model: microsoft/deberta-v3-base\n",
      "With parameters:\n",
      "Learn rate: 5e-05, Batch size: 8\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "2022-12-19 20:41:41.734819: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:41:41.740309: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:41:41.742369: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:41:41.743801: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 20:41:41.745269: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:41:41.746417: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:41:41.747980: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:41:42.132541: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:41:42.133345: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:41:42.134010: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:41:42.134600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5563 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:0b:00.0, compute capability: 8.6\n",
      "2022-12-19 20:41:42.811052: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "All model checkpoint layers were used when initializing TFDebertaV2ForSequenceClassification.\n",
      "\n",
      "Some layers of TFDebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['cls_dropout', 'classifier', 'pooler']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_tf_deberta_v2.py:125: Bernoulli.__init__ (from tensorflow.python.ops.distributions.bernoulli) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/distributions/bernoulli.py:86: Distribution.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "^C\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 393, in <module>\n",
      "    main()\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 378, in main\n",
      "    model = train_transformer(args.transformer, ep, bs, lr, sl, X_train, Y_train, X_dev, Y_dev, args.task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 178, in train_transformer\n",
      "    model.fit(tokens_train, Y_train_bin, verbose=1, epochs=epoch,\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/training.py\", line 1564, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py\", line 915, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py\", line 980, in _call\n",
      "    return self._stateless_fn(*args, **kwds)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/function.py\", line 2495, in __call__\n",
      "    filtered_flat_args) = self._maybe_define_function(args, kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/function.py\", line 2760, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/function.py\", line 2670, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1247, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/eager/def_function.py\", line 677, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1222, in autograph_handler\n",
      "    return autograph.converted_call(\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_file8vbhx81t.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options, False)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\n",
      "    return f(*args)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/training.py\", line 1146, in step_function\n",
      "    outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 1315, in run\n",
      "    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 2891, in call_for_each_replica\n",
      "    return self._call_for_each_replica(fn, args, kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 3692, in _call_for_each_replica\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 689, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 377, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 458, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/training.py\", line 1135, in run_step\n",
      "    outputs = model.train_step(data)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/transformers/modeling_tf_utils.py\", line 1520, in train_step\n",
      "    y_pred = self(x, training=True)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/training.py\", line 557, in __call__\n",
      "    return super().__call__(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/base_layer.py\", line 1097, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 689, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_filem9oxl1u8.py\", line 36, in tf__run_call_with_unpacked_inputs\n",
      "    retval_ = ag__.converted_call(ag__.ld(func), (ag__.ld(self),), dict(**ag__.ld(unpacked_inputs)), fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_filel4naa_0g.py\", line 16, in tf__call\n",
      "    outputs = ag__.converted_call(ag__.ld(self).deberta, (), dict(input_ids=ag__.ld(input_ids), attention_mask=ag__.ld(attention_mask), token_type_ids=ag__.ld(token_type_ids), position_ids=ag__.ld(position_ids), inputs_embeds=ag__.ld(inputs_embeds), output_attentions=ag__.ld(output_attentions), output_hidden_states=ag__.ld(output_hidden_states), return_dict=ag__.ld(return_dict), training=ag__.ld(training)), fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options, False)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 458, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/base_layer.py\", line 1097, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 689, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_filem9oxl1u8.py\", line 36, in tf__run_call_with_unpacked_inputs\n",
      "    retval_ = ag__.converted_call(ag__.ld(func), (ag__.ld(self),), dict(**ag__.ld(unpacked_inputs)), fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_filey3w44m_8.py\", line 92, in tf__call\n",
      "    encoder_outputs = ag__.converted_call(ag__.ld(self).encoder, (), dict(hidden_states=ag__.ld(embedding_output), attention_mask=ag__.ld(attention_mask), output_attentions=ag__.ld(output_attentions), output_hidden_states=ag__.ld(output_hidden_states), return_dict=ag__.ld(return_dict), training=ag__.ld(training)), fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options, False)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 458, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/base_layer.py\", line 1097, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 689, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_filehrcd8aqp.py\", line 99, in tf__call\n",
      "    ag__.for_stmt(ag__.converted_call(ag__.ld(enumerate), (ag__.ld(self).layer,), None, fscope), None, loop_body, get_state_4, set_state_4, ('all_attentions', 'all_hidden_states', 'output_states', 'next_kv'), {'iterate_names': '(i, layer_module)'})\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/operators/control_flow.py\", line 463, in for_stmt\n",
      "    _py_for_stmt(iter_, extra_test, body, None, None)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/operators/control_flow.py\", line 512, in _py_for_stmt\n",
      "    body(target)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/operators/control_flow.py\", line 478, in protected_body\n",
      "    original_body(protected_iter)\n",
      "  File \"/tmp/__autograph_generated_filehrcd8aqp.py\", line 61, in loop_body\n",
      "    layer_outputs = ag__.converted_call(ag__.ld(layer_module), (), dict(hidden_states=ag__.ld(next_kv), attention_mask=ag__.ld(attention_mask), query_states=ag__.ld(query_states), relative_pos=ag__.ld(relative_pos), rel_embeddings=ag__.ld(rel_embeddings), output_attentions=ag__.ld(output_attentions), training=ag__.ld(training)), fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options, False)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 458, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/base_layer.py\", line 1097, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 689, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_filesiz858ls.py\", line 10, in tf__call\n",
      "    attention_outputs = ag__.converted_call(ag__.ld(self).attention, (), dict(input_tensor=ag__.ld(hidden_states), attention_mask=ag__.ld(attention_mask), query_states=ag__.ld(query_states), relative_pos=ag__.ld(relative_pos), rel_embeddings=ag__.ld(rel_embeddings), output_attentions=ag__.ld(output_attentions), training=ag__.ld(training)), fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options, False)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 458, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/base_layer.py\", line 1097, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 689, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_file92nxn0vd.py\", line 10, in tf__call\n",
      "    self_outputs = ag__.converted_call(ag__.ld(self).self, (), dict(hidden_states=ag__.ld(input_tensor), attention_mask=ag__.ld(attention_mask), query_states=ag__.ld(query_states), relative_pos=ag__.ld(relative_pos), rel_embeddings=ag__.ld(rel_embeddings), output_attentions=ag__.ld(output_attentions), training=ag__.ld(training)), fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options, False)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 458, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/base_layer.py\", line 1097, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 689, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_filepwc3wpmq.py\", line 131, in tf__call\n",
      "    attention_probs = ag__.converted_call(ag__.ld(self).dropout, (ag__.ld(attention_probs),), dict(training=ag__.ld(training)), fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options, False)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 458, in _call_unconverted\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/engine/base_layer.py\", line 1097, in __call__\n",
      "    outputs = call_fn(inputs, *args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 689, in wrapper\n",
      "    return converted_call(f, args, kwargs, options=options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 439, in converted_call\n",
      "    result = converted_f(*effective_args, **kwargs)\n",
      "  File \"/tmp/__autograph_generated_file524ux8ml.py\", line 35, in tf__call\n",
      "    ag__.if_stmt(ag__.ld(training), if_body, else_body, get_state, set_state, ('do_return', 'retval_'), 2)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/operators/control_flow.py\", line 1363, in if_stmt\n",
      "    _py_if_stmt(cond, body, orelse)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/operators/control_flow.py\", line 1416, in _py_if_stmt\n",
      "    return body() if cond else orelse()\n",
      "  File \"/tmp/__autograph_generated_file524ux8ml.py\", line 22, in if_body\n",
      "    retval_ = ag__.converted_call(ag__.ld(self).xdropout, (ag__.ld(inputs),), None, fscope)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 377, in converted_call\n",
      "    return _call_unconverted(f, args, kwargs, options)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\n",
      "    return f(*args)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/custom_gradient.py\", line 340, in __call__\n",
      "    return self._d(self._f, a, k)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/custom_gradient.py\", line 296, in decorated\n",
      "    return _graph_mode_decorator(wrapped, args, kwargs)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/custom_gradient.py\", line 428, in _graph_mode_decorator\n",
      "    v.ref() for v in current_var_scope.global_variables() +\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/variable_scope.py\", line 1266, in global_variables\n",
      "    return self.get_collection(ops.GraphKeys.GLOBAL_VARIABLES)\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/variable_scope.py\", line 1257, in get_collection\n",
      "    scope = self._name + \"/\" if self._name else \"\"\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "\n",
    "script_name = 'models both.py'\n",
    "task = 'b'\n",
    "test_num = 3\n",
    "model_name = 'microsoft/deberta-v3-base'\n",
    "\n",
    "epochs = 10\n",
    "learning_rate = 5e-5\n",
    "batch_size = 8\n",
    "sequence_length = 100\n",
    "\n",
    "task_b_mode = ('concat', 'shuffle')\n",
    "\n",
    "tester(script_name, task, test_num, model_name, epochs, learning_rate, batch_size, sequence_length, task_b_mode)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "microsoft/deberta-v3-base\n",
      "\n",
      "Test: 4\n",
      "\n",
      "Running task B through models both.py\n",
      "The following settings are used:\n",
      " - mode: concat\n",
      " - epochs: 10\n",
      " - learning rate: 5e-05\n",
      " - batch size: 16\n",
      " - sequence length: 100\n",
      "\n",
      "\n",
      "2022-12-19 19:34:08.203427: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 19:34:08.303877: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2022-12-19 19:34:08.687970: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 19:34:08.688011: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 19:34:08.688017: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "Running deberta-v3-base for task B\n",
      "Training model: microsoft/deberta-v3-base\n",
      "With parameters:\n",
      "Learn rate: 5e-05, Batch size: 16\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "2022-12-19 19:34:12.204487: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 19:34:12.210286: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 19:34:12.212000: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 19:34:12.213741: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 19:34:12.215624: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 19:34:12.217334: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 19:34:12.218813: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 19:34:12.585323: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 19:34:12.586106: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 19:34:12.586776: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 19:34:12.587382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5665 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:0b:00.0, compute capability: 8.6\n",
      "2022-12-19 19:34:13.250654: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "All model checkpoint layers were used when initializing TFDebertaV2ForSequenceClassification.\n",
      "\n",
      "Some layers of TFDebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['pooler', 'classifier', 'cls_dropout']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_tf_deberta_v2.py:125: Bernoulli.__init__ (from tensorflow.python.ops.distributions.bernoulli) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/distributions/bernoulli.py:86: Distribution.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "700/700 [==============================] - 182s 240ms/step - loss: 0.7432 - accuracy: 0.7652 - val_loss: 0.8677 - val_accuracy: 0.7543\n",
      "Epoch 2/10\n",
      "700/700 [==============================] - 165s 236ms/step - loss: 0.7945 - accuracy: 0.7659 - val_loss: 0.8827 - val_accuracy: 0.7543\n",
      "Epoch 3/10\n",
      "700/700 [==============================] - 165s 236ms/step - loss: 0.8392 - accuracy: 0.7580 - val_loss: 0.8863 - val_accuracy: 0.7543\n",
      "Epoch 4/10\n",
      "700/700 [==============================] - 166s 237ms/step - loss: 0.8412 - accuracy: 0.7580 - val_loss: 0.8477 - val_accuracy: 0.7543\n",
      "Epoch 5/10\n",
      "700/700 [==============================] - 166s 237ms/step - loss: 0.8405 - accuracy: 0.7580 - val_loss: 0.8447 - val_accuracy: 0.7543\n",
      "Epoch 6/10\n",
      "700/700 [==============================] - 166s 237ms/step - loss: 0.8410 - accuracy: 0.7580 - val_loss: 0.8440 - val_accuracy: 0.7543\n",
      "Epoch 7/10\n",
      "700/700 [==============================] - 165s 236ms/step - loss: 0.8407 - accuracy: 0.7580 - val_loss: 0.8495 - val_accuracy: 0.7543\n",
      "Epoch 8/10\n",
      "700/700 [==============================] - 165s 236ms/step - loss: 0.8408 - accuracy: 0.7580 - val_loss: 0.8561 - val_accuracy: 0.7543\n",
      "Epoch 9/10\n",
      "700/700 [==============================] - 166s 237ms/step - loss: 0.8403 - accuracy: 0.7580 - val_loss: 0.8440 - val_accuracy: 0.7543\n",
      "Epoch 10/10\n",
      "700/700 [==============================] - 165s 236ms/step - loss: 0.8398 - accuracy: 0.7580 - val_loss: 0.8488 - val_accuracy: 0.7543\n",
      "Testing model: microsoft/deberta-v3-base on dev set\n",
      "With parameters:\n",
      "Learn rate: 5e-05, Batch size: 16\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "88/88 [==============================] - 11s 99ms/step\n",
      "Classification Report on dev set:\n",
      "                                          precision    recall  f1-score   support\n",
      "\n",
      "1. threats, plans to harm and incitement      0.000     0.000     0.000        57\n",
      "                           2. derogation      0.000     0.000     0.000       321\n",
      "                            3. animosity      0.000     0.000     0.000       242\n",
      "               4. prejudiced discussions      0.000     0.000     0.000        68\n",
      "                                    none      0.754     1.000     0.860      2112\n",
      "\n",
      "                                accuracy                          0.754      2800\n",
      "                               macro avg      0.151     0.200     0.172      2800\n",
      "                            weighted avg      0.569     0.754     0.649      2800\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/matplotlib/__init__.py\", line 649, in __setitem__\n",
      "    cval = self.validate[key](val)\n",
      "KeyError: 'font size'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 393, in <module>\n",
      "    main()\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 379, in main\n",
      "    test_transformer(args.transformer, ep, bs, lr, sl, model, X_dev, Y_dev, \"dev\", args.task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 271, in test_transformer\n",
      "    confmatrix_display(gold, pred, task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 184, in confmatrix_display\n",
      "    plt.rcParams.update({'font size': 12})\n",
      "  File \"/usr/lib/python3.10/_collections_abc.py\", line 994, in update\n",
      "    self[key] = other[key]\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/matplotlib/__init__.py\", line 654, in __setitem__\n",
      "    raise KeyError(\n",
      "KeyError: 'font size is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'\n",
      "\n",
      "\n",
      "microsoft/deberta-v3-base\n",
      "\n",
      "Test: 4\n",
      "\n",
      "Running task B through models both.py\n",
      "The following settings are used:\n",
      " - mode: shuffle\n",
      " - epochs: 10\n",
      " - learning rate: 5e-05\n",
      " - batch size: 16\n",
      " - sequence length: 100\n",
      "\n",
      "\n",
      "2022-12-19 20:02:19.832471: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 20:02:19.929463: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2022-12-19 20:02:20.311255: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 20:02:20.311297: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 20:02:20.311304: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "Running deberta-v3-base for task B\n",
      "Training model: microsoft/deberta-v3-base\n",
      "With parameters:\n",
      "Learn rate: 5e-05, Batch size: 16\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "2022-12-19 20:02:23.865861: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:02:23.871686: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:02:23.873389: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:02:23.875083: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 20:02:23.876532: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:02:23.878264: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:02:23.879736: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:02:24.239241: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:02:24.240037: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:02:24.240662: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 20:02:24.241318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5673 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:0b:00.0, compute capability: 8.6\n",
      "2022-12-19 20:02:24.897919: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "All model checkpoint layers were used when initializing TFDebertaV2ForSequenceClassification.\n",
      "\n",
      "Some layers of TFDebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['pooler', 'cls_dropout', 'classifier']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_tf_deberta_v2.py:125: Bernoulli.__init__ (from tensorflow.python.ops.distributions.bernoulli) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/distributions/bernoulli.py:86: Distribution.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "700/700 [==============================] - 181s 238ms/step - loss: 0.6972 - accuracy: 0.7805 - val_loss: 0.6218 - val_accuracy: 0.7918\n",
      "Epoch 2/10\n",
      "700/700 [==============================] - 164s 235ms/step - loss: 0.5736 - accuracy: 0.8003 - val_loss: 0.6033 - val_accuracy: 0.7800\n",
      "Epoch 3/10\n",
      "700/700 [==============================] - 164s 234ms/step - loss: 0.4715 - accuracy: 0.8230 - val_loss: 0.6169 - val_accuracy: 0.7993\n",
      "Epoch 4/10\n",
      "700/700 [==============================] - 164s 234ms/step - loss: 0.3869 - accuracy: 0.8528 - val_loss: 0.6575 - val_accuracy: 0.7946\n",
      "Epoch 5/10\n",
      "700/700 [==============================] - 164s 235ms/step - loss: 0.2945 - accuracy: 0.8840 - val_loss: 0.7950 - val_accuracy: 0.7879\n",
      "Testing model: microsoft/deberta-v3-base on dev set\n",
      "With parameters:\n",
      "Learn rate: 5e-05, Batch size: 16\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "88/88 [==============================] - 11s 99ms/step\n",
      "Classification Report on dev set:\n",
      "                                          precision    recall  f1-score   support\n",
      "\n",
      "1. threats, plans to harm and incitement      0.000     0.000     0.000        57\n",
      "                           2. derogation      0.384     0.723     0.502       321\n",
      "                            3. animosity      0.000     0.000     0.000       242\n",
      "               4. prejudiced discussions      0.000     0.000     0.000        68\n",
      "                                    none      0.889     0.924     0.906      2112\n",
      "\n",
      "                                accuracy                          0.780      2800\n",
      "                               macro avg      0.255     0.329     0.282      2800\n",
      "                            weighted avg      0.715     0.780     0.741      2800\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/matplotlib/__init__.py\", line 649, in __setitem__\n",
      "    cval = self.validate[key](val)\n",
      "KeyError: 'font size'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 393, in <module>\n",
      "    main()\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 379, in main\n",
      "    test_transformer(args.transformer, ep, bs, lr, sl, model, X_dev, Y_dev, \"dev\", args.task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 271, in test_transformer\n",
      "    confmatrix_display(gold, pred, task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 184, in confmatrix_display\n",
      "    plt.rcParams.update({'font size': 12})\n",
      "  File \"/usr/lib/python3.10/_collections_abc.py\", line 994, in update\n",
      "    self[key] = other[key]\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/matplotlib/__init__.py\", line 654, in __setitem__\n",
      "    raise KeyError(\n",
      "KeyError: 'font size is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'\n"
     ]
    }
   ],
   "source": [
    "\n",
    "script_name = 'models both.py'\n",
    "task = 'b'\n",
    "test_num = 4\n",
    "model_name = 'microsoft/deberta-v3-base'\n",
    "\n",
    "epochs = 10\n",
    "learning_rate = 5e-5\n",
    "batch_size = 16\n",
    "sequence_length = 100\n",
    "\n",
    "task_b_mode = ('concat', 'shuffle')\n",
    "\n",
    "tester(script_name, task, test_num, model_name, epochs, learning_rate, batch_size, sequence_length, task_b_mode)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# deberta 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "task b f1 macro 0.425 for concat\n",
    "\n",
    "task b f1 macro 0.431 for shuffle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "microsoft/deberta-v3-base\n",
      "\n",
      "Test: 1\n",
      "\n",
      "Running task B through models both.py\n",
      "The following settings are used:\n",
      " - mode: concat\n",
      " - epochs: 10\n",
      " - learning rate: 1e-05\n",
      " - batch size: 8\n",
      " - sequence length: 100\n",
      "\n",
      "\n",
      "2022-12-19 21:22:57.249899: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 21:22:57.350985: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2022-12-19 21:22:57.742160: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 21:22:57.742203: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 21:22:57.742210: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "Running deberta-v3-base for task B\n",
      "Training model: microsoft/deberta-v3-base\n",
      "With parameters:\n",
      "Learn rate: 1e-05, Batch size: 8\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "2022-12-19 21:23:01.326290: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:23:01.337426: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:23:01.340521: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:23:01.343118: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 21:23:01.344323: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:23:01.346586: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:23:01.356125: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:23:01.734292: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:23:01.735095: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:23:01.735761: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:23:01.736350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5595 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:0b:00.0, compute capability: 8.6\n",
      "2022-12-19 21:23:02.421774: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "All model checkpoint layers were used when initializing TFDebertaV2ForSequenceClassification.\n",
      "\n",
      "Some layers of TFDebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier', 'pooler', 'cls_dropout']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_tf_deberta_v2.py:125: Bernoulli.__init__ (from tensorflow.python.ops.distributions.bernoulli) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/distributions/bernoulli.py:86: Distribution.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "1400/1400 [==============================] - 228s 153ms/step - loss: 0.6848 - accuracy: 0.7800 - val_loss: 0.5789 - val_accuracy: 0.8043\n",
      "Epoch 2/10\n",
      "1400/1400 [==============================] - 212s 151ms/step - loss: 0.5172 - accuracy: 0.8158 - val_loss: 0.5220 - val_accuracy: 0.8086\n",
      "Epoch 3/10\n",
      "1400/1400 [==============================] - 211s 151ms/step - loss: 0.3906 - accuracy: 0.8579 - val_loss: 0.5679 - val_accuracy: 0.8107\n",
      "Epoch 4/10\n",
      "1400/1400 [==============================] - 211s 151ms/step - loss: 0.2780 - accuracy: 0.8975 - val_loss: 0.6338 - val_accuracy: 0.8207\n",
      "Epoch 5/10\n",
      "1400/1400 [==============================] - 212s 152ms/step - loss: 0.2038 - accuracy: 0.9294 - val_loss: 0.7293 - val_accuracy: 0.7964\n",
      "Testing model: microsoft/deberta-v3-base on dev set\n",
      "With parameters:\n",
      "Learn rate: 1e-05, Batch size: 8\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "88/88 [==============================] - 12s 103ms/step\n",
      "Classification Report on dev set:\n",
      "                                          precision    recall  f1-score   support\n",
      "\n",
      "1. threats, plans to harm and incitement      0.417     0.351     0.381        57\n",
      "                           2. derogation      0.456     0.639     0.532       321\n",
      "                            3. animosity      0.621     0.169     0.266       242\n",
      "               4. prejudiced discussions      0.500     0.015     0.029        68\n",
      "                                    none      0.894     0.946     0.919      2112\n",
      "\n",
      "                                accuracy                          0.809      2800\n",
      "                               macro avg      0.577     0.424     0.425      2800\n",
      "                            weighted avg      0.801     0.809     0.786      2800\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/matplotlib/__init__.py\", line 649, in __setitem__\n",
      "    cval = self.validate[key](val)\n",
      "KeyError: 'font size'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 393, in <module>\n",
      "    main()\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 379, in main\n",
      "    test_transformer(args.transformer, ep, bs, lr, sl, model, X_dev, Y_dev, \"dev\", args.task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 271, in test_transformer\n",
      "    confmatrix_display(gold, pred, task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 184, in confmatrix_display\n",
      "    plt.rcParams.update({'font size': 12})\n",
      "  File \"/usr/lib/python3.10/_collections_abc.py\", line 994, in update\n",
      "    self[key] = other[key]\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/matplotlib/__init__.py\", line 654, in __setitem__\n",
      "    raise KeyError(\n",
      "KeyError: 'font size is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'\n",
      "\n",
      "\n",
      "microsoft/deberta-v3-base\n",
      "\n",
      "Test: 1\n",
      "\n",
      "Running task B through models both.py\n",
      "The following settings are used:\n",
      " - mode: shuffle\n",
      " - epochs: 10\n",
      " - learning rate: 1e-05\n",
      " - batch size: 8\n",
      " - sequence length: 100\n",
      "\n",
      "\n",
      "2022-12-19 21:41:14.043867: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 21:41:14.143364: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2022-12-19 21:41:14.528412: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 21:41:14.528454: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n",
      "2022-12-19 21:41:14.528460: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
      "Running deberta-v3-base for task B\n",
      "Training model: microsoft/deberta-v3-base\n",
      "With parameters:\n",
      "Learn rate: 1e-05, Batch size: 8\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "2022-12-19 21:41:18.095773: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:41:18.104521: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:41:18.106019: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:41:18.107722: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-12-19 21:41:18.108691: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:41:18.113968: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:41:18.115175: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:41:18.479023: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:41:18.479815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:41:18.480416: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2022-12-19 21:41:18.480996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5564 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:0b:00.0, compute capability: 8.6\n",
      "2022-12-19 21:41:19.162200: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "All model checkpoint layers were used when initializing TFDebertaV2ForSequenceClassification.\n",
      "\n",
      "Some layers of TFDebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['cls_dropout', 'pooler', 'classifier']\n",
      "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/transformers/models/deberta_v2/modeling_tf_deberta_v2.py:125: Bernoulli.__init__ (from tensorflow.python.ops.distributions.bernoulli) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "WARNING:tensorflow:From /home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/tensorflow/python/ops/distributions/bernoulli.py:86: Distribution.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.\n",
      "Instructions for updating:\n",
      "The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.\n",
      "1400/1400 [==============================] - 227s 152ms/step - loss: 0.6858 - accuracy: 0.7798 - val_loss: 0.5807 - val_accuracy: 0.8036\n",
      "Epoch 2/10\n",
      "1400/1400 [==============================] - 209s 149ms/step - loss: 0.5159 - accuracy: 0.8188 - val_loss: 0.5231 - val_accuracy: 0.8100\n",
      "Epoch 3/10\n",
      "1400/1400 [==============================] - 210s 150ms/step - loss: 0.3892 - accuracy: 0.8585 - val_loss: 0.5681 - val_accuracy: 0.8068\n",
      "Epoch 4/10\n",
      "1400/1400 [==============================] - 204s 146ms/step - loss: 0.2753 - accuracy: 0.8986 - val_loss: 0.6520 - val_accuracy: 0.8207\n",
      "Epoch 5/10\n",
      "1400/1400 [==============================] - 200s 143ms/step - loss: 0.2080 - accuracy: 0.9274 - val_loss: 0.7227 - val_accuracy: 0.8000\n",
      "Testing model: microsoft/deberta-v3-base on dev set\n",
      "With parameters:\n",
      "Learn rate: 1e-05, Batch size: 8\n",
      "Epochs: 10, Sequence length: 100\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n",
      "88/88 [==============================] - 11s 98ms/step\n",
      "Classification Report on dev set:\n",
      "                                          precision    recall  f1-score   support\n",
      "\n",
      "1. threats, plans to harm and incitement      0.396     0.368     0.382        57\n",
      "                           2. derogation      0.461     0.623     0.530       321\n",
      "                            3. animosity      0.588     0.194     0.292       242\n",
      "               4. prejudiced discussions      0.500     0.015     0.029        68\n",
      "                                    none      0.896     0.946     0.921      2112\n",
      "\n",
      "                                accuracy                          0.810      2800\n",
      "                               macro avg      0.568     0.429     0.431      2800\n",
      "                            weighted avg      0.800     0.810     0.789      2800\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/matplotlib/__init__.py\", line 649, in __setitem__\n",
      "    cval = self.validate[key](val)\n",
      "KeyError: 'font size'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 393, in <module>\n",
      "    main()\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 379, in main\n",
      "    test_transformer(args.transformer, ep, bs, lr, sl, model, X_dev, Y_dev, \"dev\", args.task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 271, in test_transformer\n",
      "    confmatrix_display(gold, pred, task_b)\n",
      "  File \"/home/andre/Projects/uni/shared/shared-task-IS/model_testing/models both.py\", line 184, in confmatrix_display\n",
      "    plt.rcParams.update({'font size': 12})\n",
      "  File \"/usr/lib/python3.10/_collections_abc.py\", line 994, in update\n",
      "    self[key] = other[key]\n",
      "  File \"/home/andre/.local/share/virtualenvs/shared-Ch8iftQk/lib/python3.10/site-packages/matplotlib/__init__.py\", line 654, in __setitem__\n",
      "    raise KeyError(\n",
      "KeyError: 'font size is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'\n"
     ]
    }
   ],
   "source": [
    "\n",
    "script_name = 'models both.py'\n",
    "task = 'b'\n",
    "test_num = 1\n",
    "model_name = 'microsoft/deberta-v3-base'\n",
    "\n",
    "epochs = 10\n",
    "learning_rate = 1e-05\n",
    "batch_size = 8\n",
    "sequence_length = 100\n",
    "\n",
    "task_b_mode = ('concat', 'shuffle')\n",
    "\n",
    "tester(script_name, task, test_num, model_name, epochs, learning_rate, batch_size, sequence_length, task_b_mode)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.4 ('lfd')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.4"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "86d0237a3a54a747ea5eeadf5a7aab3e7ee246c76033eca4ace7d99a07ef554b"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
